package co.com.losalpes.marketplace.ws.gestionPO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionPO?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionPO", name="GestionPO")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.types.ObjectFactory.class })
public interface GestionPO
{
  @WebMethod(action="http://marketplace.losalpes.com.co/GestionPO/consultarPO")
  @Action(input="http://marketplace.losalpes.com.co/GestionPO/consultarPO", fault =
      { @FaultAction(value="http://marketplace.losalpes.com.co/GestionPO/GestionPO/consultarPO/Fault/fault",
          className=co.com.losalpes.marketplace.ws.gestionPO.ConsultarPOFault.class) },
    output="http://marketplace.losalpes.com.co/GestionPO/GestionPO/consultarPOResponse")
  @ResponseWrapper(localName="consultarPOResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOResponse")
  @RequestWrapper(localName="consultarPO", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPO")
  public void consultarPO(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimiento")
    String numSeguimiento, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="purchaseOrder", mode=Mode.OUT)
    Holder<co.com.losalpes.marketplace.ws.types.PurchaseOrder> purchaseOrder,
    @WebParam(targetNamespace="http://marketplace.losalpes.com.co", name="mensaje",
      mode=Mode.OUT)
    Holder<String> mensaje)
    throws co.com.losalpes.marketplace.ws.gestionPO.ConsultarPOFault;

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionPO/actualizarEstadoPO")
  @Action(input="http://marketplace.losalpes.com.co/GestionPO/actualizarEstadoPO",
    output="http://marketplace.losalpes.com.co/GestionPO/GestionPO/actualizarEstadoPOResponse")
  @ResponseWrapper(localName="actualizarEstadoPOResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ActualizarEstadoPOResponse")
  @RequestWrapper(localName="actualizarEstadoPO", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ActualizarEstadoPO")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="respuesta")
  public boolean actualizarEstadoPO(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimiento")
    String numSeguimiento, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="estado")
    String estado);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionPO/establecerFabricanteAtiende")
  @Action(input="http://marketplace.losalpes.com.co/GestionPO/establecerFabricanteAtiende",
    output="http://marketplace.losalpes.com.co/GestionPO/GestionPO/establecerFabricanteAtiendeResponse")
  @ResponseWrapper(localName="establecerFabricanteAtiendeResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.EstablecerFabricanteAtiendeResponse")
  @RequestWrapper(localName="establecerFabricanteAtiende",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.EstablecerFabricanteAtiende")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="Respuesta")
  public boolean establecerFabricanteAtiende(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimiento")
    String numSeguimiento, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="fabricante")
    co.com.losalpes.marketplace.ws.types.Fabricante fabricante,
    @WebParam(targetNamespace="http://marketplace.losalpes.com.co", name="items")
    co.com.losalpes.marketplace.ws.types.Item items);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionPO/registrarPO")
  @Action(input="http://marketplace.losalpes.com.co/GestionPO/registrarPO",
    output="http://marketplace.losalpes.com.co/GestionPO/GestionPO/registrarPOResponse")
  @ResponseWrapper(localName="registrarPOResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarPOResponse")
  @RequestWrapper(localName="registrarPO", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarPO")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="numSeguimiento")
  public String registrarPO(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="purchaseOrder")
    co.com.losalpes.marketplace.ws.types.PurchaseOrder purchaseOrder);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionPO/consultarComercioPO")
  @Action(input="http://marketplace.losalpes.com.co/GestionPO/consultarComercioPO",
    output="http://marketplace.losalpes.com.co/GestionPO/GestionPO/consultarComercioPOResponse")
  @ResponseWrapper(localName="consultarComercioPOResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarComercioPOResponse")
  @RequestWrapper(localName="consultarComercioPO", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarComercioPO")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="comercio")
  public co.com.losalpes.marketplace.ws.types.Comercio consultarComercioPO(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoPO")
    String numSeguimientoPO);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionPO/consultarPOsComercio")
  @Action(input="http://marketplace.losalpes.com.co/GestionPO/consultarPOsComercio",
    output="http://marketplace.losalpes.com.co/GestionPO/GestionPO/consultarPOsComercioResponse")
  @ResponseWrapper(localName="consultarPOsComercioResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarPOsComercioResponse")
  @RequestWrapper(localName="consultarPOsComercio", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOsComercio")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="pos")
  public List<co.com.losalpes.marketplace.ws.types.PurchaseOrder> consultarPOsComercio(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="nitComercio")
    String nitComercio);
}
