<wsdl:definitions
     name="PurchaseOrder"
     targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoOrdenCompra!1.0/PurchaseOrder.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="PurchaseOrder">
        <plnk:role name="PurchaseOrderProvider">
            <plnk:portType name="client:PurchaseOrder"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder"
                 schemaLocation="PurchaseOrder.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PurchaseOrderRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="PurchaseOrderResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="PurchaseOrder">
        <wsdl:operation name="process">
            <wsdl:input message="client:PurchaseOrderRequestMessage"/>
            <wsdl:output message="client:PurchaseOrderResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PurchaseOrderBinding" type="client:PurchaseOrder">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="purchaseorder_client_ep">
        <wsdl:port name="PurchaseOrder_pt" binding="client:PurchaseOrderBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorder_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
