package co.com.losalpes.marketplace.ws.contrato;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/procesocontrato_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
  name="procesocontrato_client_ep")
public class Procesocontrato_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.contrato.Procesocontrato_client_ep");
      URL baseUrl = Procesocontrato_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Procesocontrato_client_ep.class.getResource("http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/procesocontrato_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/procesocontrato_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/procesocontrato_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/procesocontrato_client_ep?WSDL",
          e);
    }
  }

  public Procesocontrato_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
                    "procesocontrato_client_ep"));
  }

  public Procesocontrato_client_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ProcesoContrato_pt")
  public co.com.losalpes.marketplace.ws.contrato.ProcesoContrato getProcesoContrato_pt()
  {
    return (co.com.losalpes.marketplace.ws.contrato.ProcesoContrato) super.getPort(new QName("http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
                                                                                             "ProcesoContrato_pt"),
                                                                                   co.com.losalpes.marketplace.ws.contrato.ProcesoContrato.class);
  }

  @WebEndpoint(name="ProcesoContrato_pt")
  public co.com.losalpes.marketplace.ws.contrato.ProcesoContrato getProcesoContrato_pt(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.contrato.ProcesoContrato) super.getPort(new QName("http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
                                                                                             "ProcesoContrato_pt"),
                                                                                   co.com.losalpes.marketplace.ws.contrato.ProcesoContrato.class,
                                                                                   features);
  }
}
