package co.com.losalpes.marketplace.ws.gestionPO;


import co.com.losalpes.marketplace.ws.gestionPO.PoManagerPoManagementService;
import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class PoManagerPoManagementPortClient
{
  @WebServiceRef
  private static PoManagerPoManagementService poManagerPoManagementService;

    public static PoManagerPoManagement getGestionPO()
    {
        poManagerPoManagementService = new PoManagerPoManagementService();
        PoManagerPoManagement poManagerPoManagement = poManagerPoManagementService.getPoManagerPoManagementPort();
      return poManagerPoManagement;
    }
}
