package co.com.losalpes.marketplace.ws.ldapRol;

import javax.xml.ws.WebFault;

@WebFault(faultBean="co.com.losalpes.marketplace.ws.ldapRol.types.EstadoNoExisteException",
  targetNamespace="http://ws.ldap.marketplace.losalpes.com.co/", name="EstadoNoExisteException")
public class EstadoNoExisteException
  extends Exception
{
  private co.com.losalpes.marketplace.ws.ldapRol.types.EstadoNoExisteException faultInfo;

  public EstadoNoExisteException(String message,
                                 co.com.losalpes.marketplace.ws.ldapRol.types.EstadoNoExisteException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public EstadoNoExisteException(String message,
                                 co.com.losalpes.marketplace.ws.ldapRol.types.EstadoNoExisteException faultInfo,
                                 Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public co.com.losalpes.marketplace.ws.ldapRol.types.EstadoNoExisteException getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(co.com.losalpes.marketplace.ws.ldapRol.types.EstadoNoExisteException faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
