package co.com.losalpes.marketplace.ws.ordenCompra;

import co.com.losalpes.marketplace.ws.types.ObjectFactory;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoOrdenCompraSubasta/ordencomprasubasta_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
  name="OrdenCompraSubasta")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface OrdenCompraSubasta
{
  @WebMethod(action="process")
  @Action(input="process")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
    className="co.com.losalpes.marketplace.ws.ordenCompra.types.Process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="fechaMaximaEntrega")
    XMLGregorianCalendar fechaMaximaEntrega, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="fechaMaximaSubasta")
    XMLGregorianCalendar fechaMaximaSubasta, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="fecha")
    XMLGregorianCalendar fecha, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="nitComercio")
    String nitComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="nombreComercio")
    String nombreComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="emailComercio")
    String emailComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="direccionComercio")
    String direccionComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="telefonoComercio")
    String telefonoComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="cantidadProducto")
    int cantidadProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="nombreProducto")
    String nombreProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompraSubasta/OrdenCompraSubasta",
      name="categoriaProducto")
    String categoriaProducto);
}
