package co.com.losalpes.marketplace.ws.gestionSubasta;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionSubasta?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionOfertas",
  name="GestionSubastaSOAPQSService")
public class GestionSubastaSOAPQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubastaSOAPQSService");
      URL baseUrl = GestionSubastaSOAPQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GestionSubastaSOAPQSService.class.getResource("http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionSubasta?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionSubasta?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionSubasta?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionSubasta?wsdl",
          e);
    }
  }

  public GestionSubastaSOAPQSService()
  {
    super(wsdlLocationURL,
          new QName("http://marketplace.losalpes.com.co/GestionOfertas",
                    "GestionSubastaSOAPQSService"));
  }

  public GestionSubastaSOAPQSService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GestionSubastaSOAPQSPort")
  public co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubasta getGestionSubastaSOAPQSPort()
  {
    return (co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubasta) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionOfertas",
                                                                                                  "GestionSubastaSOAPQSPort"),
                                                                                        co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubasta.class);
  }

  @WebEndpoint(name="GestionSubastaSOAPQSPort")
  public co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubasta getGestionSubastaSOAPQSPort(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubasta) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionOfertas",
                                                                                                  "GestionSubastaSOAPQSPort"),
                                                                                        co.com.losalpes.marketplace.ws.gestionSubasta.GestionSubasta.class,
                                                                                        features);
  }
}
