package co.com.losalpes.marketplace.ldap;

import javax.xml.ws.WebFault;

@WebFault(faultBean="co.com.losalpes.marketplace.ldap.types.UsuarioNoExisteException",
  targetNamespace="http://ws.ldap.marketplace.losalpes.com.co/", name="UsuarioNoExisteException")
public class UsuarioNoExisteException
  extends Exception
{
  private co.com.losalpes.marketplace.ldap.types.UsuarioNoExisteException faultInfo;

  public UsuarioNoExisteException(String message,
                                  co.com.losalpes.marketplace.ldap.types.UsuarioNoExisteException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public UsuarioNoExisteException(String message,
                                  co.com.losalpes.marketplace.ldap.types.UsuarioNoExisteException faultInfo,
                                  Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public co.com.losalpes.marketplace.ldap.types.UsuarioNoExisteException getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(co.com.losalpes.marketplace.ldap.types.UsuarioNoExisteException faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
