package co.com.losalpes.marketplace.ws.confirmacionPago;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoFacturacion/confirmacionpago_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoFacturacion/ConfirmacionPago",
  name="ConfirmacionPago")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.confirmacionPago.types.ObjectFactory.class })
public interface ConfirmacionPago
{
  @WebMethod(action="process")
  @Action(input="process")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoFacturacion/ConfirmacionPago",
    className="co.com.losalpes.marketplace.ws.confirmacionPago.types.Process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoFacturacion/ConfirmacionPago",
      name="numCuenta")
    String numCuenta, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoFacturacion/ConfirmacionPago",
      name="valor")
    long valor, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoFacturacion/ConfirmacionPago",
      name="descripcion")
    String descripcion, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoFacturacion/ConfirmacionPago",
      name="referencia")
    String referencia);
}
