<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="http://localhost:7001/marketPlace/proxy/GestionSubasta?wsdl"/>
      <rootElement name="crearSubastaResponse" namespace="http://marketplace.losalpes.com.co"/>
    </source>
    <source type="WSDL">
      <schema location="http://localhost:7001/marketPlace/proxy/GestionCliente?wsdl"/>
      <rootElement name="consultarClientesProductoResponse" namespace="http://marketplace.losalpes.com.co"/>
      <param name="ObtenerFabricantes_ConsultarClientesProducto_OutputVariable.parameters" />
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="http://localhost:7001/marketPlace/proxy/GestionSubasta?wsdl"/>
      <rootElement name="asignarFabricantesSubasta" namespace="http://marketplace.losalpes.com.co"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.5.0(build 110418.1550.0174) AT [SUN OCT 16 00:44:57 COT 2011]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:ns1="http://ws.transact.marketplace.losalpes.com.co/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://marketplace.losalpes.com.co/GestionCliente"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:tns="http://marketplace.losalpes.com.co/GestionOfertas"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd1="http://marketplace.losalpes.com.co"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns1 ns0 tns xsd1 xsd soap wsdl bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap">
  <xsl:param name="ObtenerFabricantes_ConsultarClientesProducto_OutputVariable.parameters"/>
  <xsl:template match="/">
    <xsd1:asignarFabricantesSubasta>
      <xsd1:numSeguimientoSubasta>
        <xsl:value-of select="/xsd1:crearSubastaResponse/xsd1:numSeguimientoSub"/>
      </xsd1:numSeguimientoSubasta>
      <xsl:for-each select="$ObtenerFabricantes_ConsultarClientesProducto_OutputVariable.parameters/xsd1:consultarClientesProductoResponse/xsd1:cliente">
        <xsd1:fabricantes>
          <nit>
            <xsl:value-of select="nit"/>
          </nit>
        </xsd1:fabricantes>
      </xsl:for-each>
    </xsd1:asignarFabricantesSubasta>
  </xsl:template>
</xsl:stylesheet>
