package co.com.losalpes.marketplace.ws.registro;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoRegistro/registroentidad_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
  name="RegistroEntidad")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.registro.types.ObjectFactory.class })
public interface RegistroEntidad
{
  @WebMethod(action="process")
  @Action(input="process")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
    className="co.com.losalpes.marketplace.ws.registro.types.Process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="nit")
    String nit, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="nombre")
    String nombre, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="direccion")
    String direccion, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="telefono")
    String telefono, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="email")
    String email, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="tipo")
    String tipo, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="razonSocial")
    String razonSocial, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="contactos")
    List<co.com.losalpes.marketplace.ws.registro.types.ContactoCliente> contactos,
    @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="fecha")
    XMLGregorianCalendar fecha, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="documentos")
    List<co.com.losalpes.marketplace.ws.registro.types.DocumentoSolicitud> documentos,
    @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad",
      name="productos")
    List<co.com.losalpes.marketplace.ws.registro.types.ProductoSolicitud> productos);
}
