package co.com.losalpes.marketplace.ws.gestionPO;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionPO?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionPO", name="GestionPO")
public class GestionPO_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionPO.GestionPO_Service");
      URL baseUrl = GestionPO_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GestionPO_Service.class.getResource("http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionPO?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionPO?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionPO?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionPO?wsdl",
          e);
    }
  }

  public GestionPO_Service()
  {
    super(wsdlLocationURL,
          new QName("http://marketplace.losalpes.com.co/GestionPO",
                    "GestionPO"));
  }

  public GestionPO_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GestionPOSOAP")
  public co.com.losalpes.marketplace.ws.gestionPO.GestionPO getGestionPOSOAP()
  {
    return (co.com.losalpes.marketplace.ws.gestionPO.GestionPO) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionPO",
                                                                                        "GestionPOSOAP"),
                                                                              co.com.losalpes.marketplace.ws.gestionPO.GestionPO.class);
  }

  @WebEndpoint(name="GestionPOSOAP")
  public co.com.losalpes.marketplace.ws.gestionPO.GestionPO getGestionPOSOAP(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.gestionPO.GestionPO) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionPO",
                                                                                        "GestionPOSOAP"),
                                                                              co.com.losalpes.marketplace.ws.gestionPO.GestionPO.class,
                                                                              features);
  }
}
