package co.com.losalpes.marketplace.ws.gestionRMA;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class GestionRMASOAPClient
{
  @WebServiceRef
  private static GestionRMA_Service gestionRMA_Service;

  public static GestionRMA getGestionRMA()
  {
    gestionRMA_Service = new GestionRMA_Service();
    GestionRMA gestionRMA = gestionRMA_Service.getGestionRMASOAP();
    return gestionRMA;
  }
}
