package co.com.losalpes.marketplace.ws.gestionDA;

import co.com.losalpes.marketplace.ws.types.DispatchAdvice;
import co.com.losalpes.marketplace.ws.types.ObjectFactory;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionDA?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionDA", name="GestionDA")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface GestionDA
{
  @WebMethod(action="http://marketplace.losalpes.com.co/GestionDA/registrarDA")
  @Action(input="http://marketplace.losalpes.com.co/GestionDA/registrarDA",
    output="http://marketplace.losalpes.com.co/GestionDA/GestionDA/registrarDAResponse")
  @ResponseWrapper(localName="registrarDAResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarDAResponse")
  @RequestWrapper(localName="registrarDA", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarDA")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="numSeguimiento")
  public String registrarDA(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoPo")
    String numSeguimientoPo, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="da")
    DispatchAdvice da);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionDA/consultarDA")
  @Action(input="http://marketplace.losalpes.com.co/GestionDA/consultarDA",
    output="http://marketplace.losalpes.com.co/GestionDA/GestionDA/consultarDAResponse")
  @ResponseWrapper(localName="consultarDAResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarDAResponse")
  @RequestWrapper(localName="consultarDA", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarDA")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="da")
  public DispatchAdvice consultarDA(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimiento")
    String numSeguimiento);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionDA/consultarDAsFabricante")
  @Action(input="http://marketplace.losalpes.com.co/GestionDA/consultarDAsFabricante",
    output="http://marketplace.losalpes.com.co/GestionDA/GestionDA/consultarDAsFabricanteResponse")
  @ResponseWrapper(localName="consultarDAsFabricanteResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarDAsFabricanteResponse")
  @RequestWrapper(localName="consultarDAsFabricante", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarDAsFabricante")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="das")
  public List<DispatchAdvice> consultarDAsFabricante(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="nit")
    String nit);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionDA/consultarDAnumSeguimientoPO")
  @Action(input="http://marketplace.losalpes.com.co/GestionDA/consultarDAnumSeguimientoPO",
    output="http://marketplace.losalpes.com.co/GestionDA/GestionDA/consultarDAnumSeguimientoPOResponse")
  @ResponseWrapper(localName="consultarDAnumSeguimientoPOResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarDAnumSeguimientoPOResponse")
  @RequestWrapper(localName="consultarDAnumSeguimientoPO",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarDAnumSeguimientoPO")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="da")
  public DispatchAdvice consultarDAnumSeguimientoPO(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoPO")
    String numSeguimientoPO);
}
