package co.com.co.com;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class GestionClienteSOAPClient
{
  @WebServiceRef
  private static GestionCliente_Service gestionCliente_Service;

  public static void main(String [] args)
  {
    gestionCliente_Service = new GestionCliente_Service();
    GestionCliente gestionCliente = gestionCliente_Service.getGestionClienteSOAP();
    // Add your code to call the desired methods.
  }
}
