package co.com.losalpes.marketplace.ws.gestionPO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionPO?wsdl",
  targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
  name="PoManagerPoManagement")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.types.ObjectFactory.class })
public interface PoManagerPoManagement
{
  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/registrarPORequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/registrarPO/Fault/BussinessException",
          className=BussinessException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/registrarPOResponse")
  @ResponseWrapper(localName="registrarPOResponse", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.RegistrarPOResponse")
  @RequestWrapper(localName="registrarPO", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.RegistrarPO")
  @WebResult(targetNamespace="")
  public String registrarPO(@WebParam(targetNamespace="", name="purchaseOrderBO")
    co.com.losalpes.marketplace.ws.types.PurchaseOrderBO purchaseOrderBO)
    throws BussinessException;

  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOFabricantePorEstadoRequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOFabricantePorEstado/Fault/BussinessException",
          className=BussinessException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOFabricantePorEstadoResponse")
  @ResponseWrapper(localName="consultarPOFabricantePorEstadoResponse",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOFabricantePorEstadoResponse")
  @RequestWrapper(localName="consultarPOFabricantePorEstado",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOFabricantePorEstado")
  @WebResult(targetNamespace="")
  public List<co.com.losalpes.marketplace.ws.types.PurchaseOrderBO> consultarPOFabricantePorEstado(@WebParam(targetNamespace="",
      name="nit")
    String nit, @WebParam(targetNamespace="", name="estado")
    String estado)
    throws BussinessException;

  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPORequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPO/Fault/OrdenCompraNoExisteException",
          className=OrdenCompraNoExisteException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOResponse")
  @ResponseWrapper(localName="consultarPOResponse", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOResponse")
  @RequestWrapper(localName="consultarPO", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPO")
  @WebResult(targetNamespace="")
  public co.com.losalpes.marketplace.ws.types.PurchaseOrderBO consultarPO(@WebParam(targetNamespace="",
      name="numSeguimiento")
    String numSeguimiento)
    throws OrdenCompraNoExisteException;

  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/actualizarEstadoPORequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/actualizarEstadoPO/Fault/OrdenCompraNoExisteException",
          className=OrdenCompraNoExisteException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/actualizarEstadoPOResponse")
  @ResponseWrapper(localName="actualizarEstadoPOResponse",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ActualizarEstadoPOResponse")
  @RequestWrapper(localName="actualizarEstadoPO", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ActualizarEstadoPO")
  @WebResult(targetNamespace="")
  public boolean actualizarEstadoPO(@WebParam(targetNamespace="", name="numSeguimiento")
    String numSeguimiento, @WebParam(targetNamespace="", name="estado")
    String estado)
    throws OrdenCompraNoExisteException;

  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/establecerFabricanteAtiendeRequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/establecerFabricanteAtiende/Fault/OrdenCompraNoExisteException",
          className=OrdenCompraNoExisteException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/establecerFabricanteAtiendeResponse")
  @ResponseWrapper(localName="establecerFabricanteAtiendeResponse",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.EstablecerFabricanteAtiendeResponse")
  @RequestWrapper(localName="establecerFabricanteAtiende",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.EstablecerFabricanteAtiende")
  @WebResult(targetNamespace="")
  public boolean establecerFabricanteAtiende(@WebParam(targetNamespace="",
      name="numSeguimiento")
    String numSeguimiento, @WebParam(targetNamespace="", name="fabricante")
    co.com.losalpes.marketplace.ws.types.FabricanteBO fabricante,
    @WebParam(targetNamespace="", name="productosAtiende")
    List<co.com.losalpes.marketplace.ws.types.ProductoBO> productosAtiende)
    throws OrdenCompraNoExisteException;

  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarComercioPorPORequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarComercioPorPO/Fault/OrdenCompraNoExisteException",
          className=OrdenCompraNoExisteException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarComercioPorPOResponse")
  @ResponseWrapper(localName="consultarComercioPorPOResponse",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarComercioPorPOResponse")
  @RequestWrapper(localName="consultarComercioPorPO", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarComercioPorPO")
  @WebResult(targetNamespace="")
  public co.com.losalpes.marketplace.ws.types.ComercioBO consultarComercioPorPO(@WebParam(targetNamespace="",
      name="numSeguimiento")
    String numSeguimiento)
    throws OrdenCompraNoExisteException;

  @WebMethod
  @Action(input="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOsComercioRequest", fault =
      { @FaultAction(value="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOsComercio/Fault/ClienteNoExisteException",
          className=ClienteNoExisteException.class) },
    output="http://ws.pomanager.marketplace.losalpes.com.co/PoManagerPoManagement/consultarPOsComercioResponse")
  @ResponseWrapper(localName="consultarPOsComercioResponse",
    targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOsComercioResponse")
  @RequestWrapper(localName="consultarPOsComercio", targetNamespace="http://ws.pomanager.marketplace.losalpes.com.co/",
    className="co.com.losalpes.marketplace.ws.types.ConsultarPOsComercio")
  @WebResult(targetNamespace="")
  public List<co.com.losalpes.marketplace.ws.types.PurchaseOrderBO> consultarPOsComercio(@WebParam(targetNamespace="",
      name="nit")
    String nit)
    throws ClienteNoExisteException;
}
