package co.com.losalpes.marketplace.ws.retornoMaterial;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoRetornoMaterial/returnmaterialadvice_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
  name="ReturnMaterialAdvice")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.retornoMaterial.types.ObjectFactory.class })
public interface ReturnMaterialAdvice
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice/ReturnMaterialAdvice/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
    className="co.com.losalpes.marketplace.ws.retornoMaterial.types.ProcessResponse")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
    className="co.com.losalpes.marketplace.ws.retornoMaterial.types.Process")
  @WebResult(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
    name="numSeguimientoRMA")
  public String process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="causa")
    String causa, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="fecha")
    XMLGregorianCalendar fecha, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="cantidadProducto")
    int cantidadProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="valorProducto")
    long valorProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="nombreProducto")
    String nombreProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="categoriaProducto")
    String categoriaProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="referenciaProducto")
    String referenciaProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="numSeguimientoPO")
    String numSeguimientoPO, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice",
      name="numSeguimientoDA")
    String numSeguimientoDA);
}
