<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="AprobarContrato"
     targetNamespace="http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato"
     xmlns:tns="http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato"
                 schemaLocation="xsd/ProcesoContrato.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:process"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="AprobarDesaprobar">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
        <wsdl:operation name="CerrarContrato">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
