package co.com.losalpes.marketplace.ws.gestionContrato;

import javax.xml.ws.WebFault;

@WebFault(faultBean="co.com.losalpes.marketplace.ws.types.ContratoException",
  targetNamespace="http://ws.contractmanager.marketplace.losalpes.com.co/",
  name="ContratoException")
public class ContratoException
  extends Exception
{
  private co.com.losalpes.marketplace.ws.types.ContratoException faultInfo;

  public ContratoException(String message,
                           co.com.losalpes.marketplace.ws.types.ContratoException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public ContratoException(String message,
                           co.com.losalpes.marketplace.ws.types.ContratoException faultInfo,
                           Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public co.com.losalpes.marketplace.ws.types.ContratoException getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(co.com.losalpes.marketplace.ws.types.ContratoException faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
