package co.com.losalpes.marketplace.ws.gestionContrato;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://localhost:7001/marketPlace/proxy/GestionContrato?wsdl",
  targetNamespace="http://ws.contractmanager.marketplace.losalpes.com.co/",
  name="ContractManagerContractManagementService")
public class ContractManagerContractManagementService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagementService");
      URL baseUrl =
        ContractManagerContractManagementService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ContractManagerContractManagementService.class.getResource("http://localhost:7001/marketPlace/proxy/GestionContrato?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7001/marketPlace/proxy/GestionContrato?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost:7001/marketPlace/proxy/GestionContrato?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7001/marketPlace/proxy/GestionContrato?wsdl",
          e);
    }
  }

  public ContractManagerContractManagementService()
  {
    super(wsdlLocationURL,
          new QName("http://ws.contractmanager.marketplace.losalpes.com.co/",
                    "ContractManagerContractManagementService"));
  }

  public ContractManagerContractManagementService(URL wsdlLocation,
                                                  QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ContractManagerContractManagementPort")
  public co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagement getContractManagerContractManagementPort()
  {
    return (co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagement) super.getPort(new QName("http://ws.contractmanager.marketplace.losalpes.com.co/",
                                                                                                                      "ContractManagerContractManagementPort"),
                                                                                                            co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagement.class);
  }

  @WebEndpoint(name="ContractManagerContractManagementPort")
  public co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagement getContractManagerContractManagementPort(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagement) super.getPort(new QName("http://ws.contractmanager.marketplace.losalpes.com.co/",
                                                                                                                      "ContractManagerContractManagementPort"),
                                                                                                            co.com.losalpes.marketplace.ws.gestionContrato.ContractManagerContractManagement.class,
                                                                                                            features);
  }
}
