package co.com.co.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/marketPlace/proxy/GestionCliente?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionCliente",
  name="GestionCliente")
@XmlSeeAlso(
  { co.com.co.com.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface GestionCliente
{
  @WebMethod(operationName="CrearCliente", action="http://marketplace.losalpes.com.co/GestionCliente/CrearCliente")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/CrearCliente",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/CrearClienteResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="crearClienteResponse")
  public co.com.co.com.types.CrearClienteResponse crearCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="crearCliente")
    co.com.co.com.types.CrearCliente parameters);

  @WebMethod(operationName="CrearContactos", action="http://marketplace.losalpes.com.co/GestionCliente/CrearContactos")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/CrearContactos",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/CrearContactosResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="crearContactoResponse")
  public co.com.co.com.types.CrearContactoResponse crearContactos(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="crearContacto")
    co.com.co.com.types.CrearContacto parameters);

  @WebMethod(operationName="ConsultarCliente", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarCliente")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarCliente",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarClienteResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarClienteResponse")
  public co.com.co.com.types.ConsultarClienteResponse consultarCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarCliente")
    co.com.co.com.types.ConsultarCliente parameters);

  @WebMethod(operationName="ConsultarClientes", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarClientes")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarClientes",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarClientesResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarClientesResponse")
  public co.com.co.com.types.ConsultarClientesResponse consultarClientes(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarClientes")
    co.com.co.com.types.ConsultarClientes parameters);

  @WebMethod(operationName="ConsultarComision", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarComision")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarComision",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarComisionResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarComisionResponse")
  public co.com.co.com.types.ConsultarComisionResponse consultarComision(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarComision")
    co.com.co.com.types.ConsultarComision parameters);

  @WebMethod(operationName="ModificarCliente", action="http://marketplace.losalpes.com.co/GestionCliente/ModificarCliente")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ModificarCliente",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ModificarClienteResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="modificarClienteResponse")
  public co.com.co.com.types.ModificarClienteResponse modificarCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="modificarCliente")
    co.com.co.com.types.ModificarCliente parameters);

  @WebMethod(operationName="ModificarComision", action="http://marketplace.losalpes.com.co/GestionCliente/ModificarComision")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ModificarComision",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ModificarComisionResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="modificarComisionResponse")
  public co.com.co.com.types.ModificarComisionResponse modificarComision(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="modificarComision")
    co.com.co.com.types.ModificarComision parameters);

  @WebMethod(operationName="ConsultarClientesProducto", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarClientesProducto")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarClientesProducto",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarClientesProductoResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarClientesProductoResponse")
  public co.com.co.com.types.ConsultarClientesProductoResponse consultarClientesProducto(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarClientesProducto")
    co.com.co.com.types.ConsultarClientesProducto parameters);

  @WebMethod(operationName="RadicarSolicitud", action="http://marketplace.losalpes.com.co/GestionCliente/RadicarSolicitud")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/RadicarSolicitud",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/RadicarSolicitudResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="radicarSolicitudResponse")
  public co.com.co.com.types.RadicarSolicitudResponse radicarSolicitud(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="radicarSolicitud")
    co.com.co.com.types.RadicarSolicitud parameters);

  @WebMethod(operationName="ActualizarSolicitud", action="http://marketplace.losalpes.com.co/GestionCliente/ActualizarSolicitud")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ActualizarSolicitud",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ActualizarSolicitudResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="actualizarSolicitudResponse")
  public co.com.co.com.types.ActualizarSolicitudResponse actualizarSolicitud(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="actualizarSolicitud")
    co.com.co.com.types.ActualizarSolicitud parameters);

  @WebMethod(operationName="ActualizarEstadoCliente", action="http://marketplace.losalpes.com.co/GestionCliente/ActualizarEstadoCliente")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ActualizarEstadoCliente",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ActualizarEstadoClienteResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="actualizarEstadoClienteResponse")
  public co.com.co.com.types.ActualizarEstadoClienteResponse actualizarEstadoCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="actualizarEstadoCliente")
    co.com.co.com.types.ActualizarEstadoCliente parameters);

  @WebMethod(operationName="ActualizarEstadoSolicitud", action="http://marketplace.losalpes.com.co/GestionCliente/ActualizarEstadoSolicitud")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ActualizarEstadoSolicitud",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ActualizarEstadoSolicitudResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="actualizarEstadoSolicitudResponse")
  public co.com.co.com.types.ActualizarEstadoSolicitudResponse actualizarEstadoSolicitud(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="actualizarEstadoSolicitud")
    co.com.co.com.types.ActualizarEstadoSolicitud parameters);

  @WebMethod(operationName="CerrarSolicitud", action="http://marketplace.losalpes.com.co/GestionCliente/CerrarSolicitud")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/CerrarSolicitud",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/CerrarSolicitudResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="cerrarSolicitudResponse")
  public co.com.co.com.types.CerrarSolicitudResponse cerrarSolicitud(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="cerrarSolicitud")
    co.com.co.com.types.CerrarSolicitud parameters);

  @WebMethod(operationName="ConsultarProductosCliente", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarProductosCliente")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarProductosCliente",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarProductosClienteResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarProductosClienteResponse")
  public co.com.co.com.types.ConsultarProductosClienteResponse consultarProductosCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarProductosCliente")
    co.com.co.com.types.ConsultarProductosCliente parameters);

  @WebMethod(operationName="ConsultarContacto", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarContacto")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarContacto",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarContactoResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarContactoResponse")
  public co.com.co.com.types.ConsultarContactoResponse consultarContacto(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarContacto")
    co.com.co.com.types.ConsultarContacto parameters);

  @WebMethod(operationName="CrearProductos", action="http://marketplace.losalpes.com.co/GestionCliente/CrearProductos")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/CrearProductos",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/CrearProductosResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="crearProductoResponse")
  public co.com.co.com.types.CrearProductoResponse crearProductos(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="crearProducto")
    co.com.co.com.types.CrearProducto parameters);

  @WebMethod(operationName="ModificarContacto", action="http://marketplace.losalpes.com.co/GestionCliente/ModificarContacto")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ModificarContacto",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ModificarContactoResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="modificarContactoResponse")
  public co.com.co.com.types.ModificarContactoResponse modificarContacto(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="modificarContacto")
    co.com.co.com.types.ModificarContacto parameters);

  @WebMethod(operationName="ConsultarProducto", action="http://marketplace.losalpes.com.co/GestionCliente/ConsultarProducto")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ConsultarProducto",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ConsultarProductoResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="consultarProductoResponse")
  public co.com.co.com.types.ConsultarProductoResponse consultarProducto(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="consultarProducto")
    co.com.co.com.types.ConsultarProducto parameters);

  @WebMethod(operationName="ModificarProducto", action="http://marketplace.losalpes.com.co/GestionCliente/ModificarProducto")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://marketplace.losalpes.com.co/GestionCliente/ModificarProducto",
    output="http://marketplace.losalpes.com.co/GestionCliente/GestionCliente/ModificarProductoResponse")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co",
    partName="parameters", name="modificarProductoResponse")
  public co.com.co.com.types.ModificarProductoResponse modificarProducto(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      partName="parameters", name="modificarProducto")
    co.com.co.com.types.ModificarProducto parameters);
}
