package co.com.losalpes.marketplace.ws.gestionSubasta;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class GestionSubastaSOAPQSPortClient
{
  @WebServiceRef
  private static GestionSubastaSOAPQSService gestionSubastaSOAPQSService;

  public static void main(String [] args)
  {
    gestionSubastaSOAPQSService = new GestionSubastaSOAPQSService();
    GestionSubasta gestionSubasta = gestionSubastaSOAPQSService.getGestionSubastaSOAPQSPort();
    // Add your code to call the desired methods.
  }
  
  public static GestionSubasta getGestionSubasta()
  {
          gestionSubastaSOAPQSService = new GestionSubastaSOAPQSService();
          GestionSubasta gestionSubasta = gestionSubastaSOAPQSService.getGestionSubastaSOAPQSPort();
          return gestionSubasta;
  }
  
}
