package co.com.losalpes.marketplace.ws.gestionFacturacion;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionFacturacion?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionFacturacion",
  name="GestionFacturacion")
public class GestionFacturacion_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionFacturacion.GestionFacturacion_Service");
      URL baseUrl = GestionFacturacion_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GestionFacturacion_Service.class.getResource("http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionFacturacion?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionFacturacion?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionFacturacion?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionFacturacion?wsdl",
          e);
    }
  }

  public GestionFacturacion_Service()
  {
    super(wsdlLocationURL,
          new QName("http://marketplace.losalpes.com.co/GestionFacturacion",
                    "GestionFacturacion"));
  }

  public GestionFacturacion_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GestionFacturacionSOAP")
  public GestionFacturacion getGestionFacturacionSOAP()
  {
    return (GestionFacturacion) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionFacturacion",
                                                        "GestionFacturacionSOAP"),
                                              GestionFacturacion.class);
  }

  @WebEndpoint(name="GestionFacturacionSOAP")
  public GestionFacturacion getGestionFacturacionSOAP(WebServiceFeature... features)
  {
    return (GestionFacturacion) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionFacturacion",
                                                        "GestionFacturacionSOAP"),
                                              GestionFacturacion.class,
                                              features);
  }
}
