<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions name="GestionCorreoElectronico" targetNamespace="http://marketplace.losalpes.com.co/GestionCorreoElectronico" xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/" xmlns:WL5G3N1="http://marketplace.losalpes.com.co" xmlns:WL5G3N2="http://marketplace.losalpes.com.co/GestionCorreoElectronico" xmlns:WL5G3N3="http://schemas.xmlsoap.org/wsdl/soap/">
  <WL5G3N0:types>
    <xsd:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://marketplace.losalpes.com.co/GestionCorreoElectronico" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="http://marketplace.losalpes.com.co">
      <xsd:import namespace="http://marketplace.losalpes.com.co" schemaLocation="GestionCorreoElectronico.xsd">
    	</xsd:import>
    </xsd:schema>
  </WL5G3N0:types>
  <WL5G3N0:message name="enviarCorreoElectronicoRequest">
    <WL5G3N0:part element="WL5G3N1:enviarCorreoElectronico" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:message name="enviarCorreoElectronicoResponse">
    <WL5G3N0:part element="WL5G3N1:enviarCorreoElectronicoResponse" name="parameters"/>
  </WL5G3N0:message>
  <WL5G3N0:portType name="GestionCorreoElectronico">
    <WL5G3N0:operation name="enviarCorreoElectronico">
      <WL5G3N0:input message="WL5G3N2:enviarCorreoElectronicoRequest"/>
      <WL5G3N0:output message="WL5G3N2:enviarCorreoElectronicoResponse"/>
    </WL5G3N0:operation>
  </WL5G3N0:portType>
  <WL5G3N0:binding name="GestionCorreoElectronicoSOAP" type="WL5G3N2:GestionCorreoElectronico">
    <WL5G3N3:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <WL5G3N0:operation name="enviarCorreoElectronico">
      <WL5G3N3:operation soapAction="http://marketplace.losalpes.com.co/GestionCorreoElectronico/enviarCorreoElectronico"/>
      <WL5G3N0:input>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:input>
      <WL5G3N0:output>
        <WL5G3N3:body use="literal"/>
      </WL5G3N0:output>
    </WL5G3N0:operation>
  </WL5G3N0:binding>
  <WL5G3N0:service name="GestionCorreoElectronico">
    <WL5G3N0:port binding="WL5G3N2:GestionCorreoElectronicoSOAP" name="GestionCorreoElectronicoSOAP">
      <WL5G3N3:address location="http://User-PC:7001/marketPlace/proxy/GestionCorreoElectronico"/>
    </WL5G3N0:port>
  </WL5G3N0:service>
</WL5G3N0:definitions>