package co.com.losalpes.marketplace.ws.gestionSubasta;

import co.com.losalpes.marketplace.ws.types.Fabricante;
import co.com.losalpes.marketplace.ws.types.ObjectFactory;
import co.com.losalpes.marketplace.ws.types.PurchaseOrder;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionSubasta?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionOfertas",
  name="GestionSubasta")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface GestionSubasta
{
  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/registrarOferta")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/registrarOferta",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/registrarOfertaResponse")
  @ResponseWrapper(localName="registrarOfertaResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarOfertaResponse")
  @RequestWrapper(localName="registrarOferta", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarOferta")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean registrarOferta(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="oferta")
    co.com.losalpes.marketplace.ws.types.Oferta oferta,
    @WebParam(targetNamespace="http://marketplace.losalpes.com.co", name="numSeguimientoSub")
    String numSeguimientoSub);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/cerrarSubasta")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/cerrarSubasta",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/cerrarSubastaResponse")
  @ResponseWrapper(localName="cerrarSubastaResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.CerrarSubastaResponse")
  @RequestWrapper(localName="cerrarSubasta", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.CerrarSubasta")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean cerrarSubasta(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoSub")
    String numSeguimientoSub);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/darGanadorSubasta")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/darGanadorSubasta",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/darGanadorSubastaResponse")
  @ResponseWrapper(localName="darGanadorSubastaResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.DarGanadorSubastaResponse")
  @RequestWrapper(localName="darGanadorSubasta", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.DarGanadorSubasta")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="fabricante")
  public Fabricante darGanadorSubasta(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoSub")
    String numSeguimientoSub);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/crearSubasta")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/crearSubasta",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/crearSubastaResponse")
  @ResponseWrapper(localName="crearSubastaResponse", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.CrearSubastaResponse")
  @RequestWrapper(localName="crearSubasta", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.CrearSubasta")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="numSeguimientoSub")
  public String crearSubasta(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="po")
    PurchaseOrder po);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/consultarSubastasFabricante")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/consultarSubastasFabricante",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/consultarSubastasFabricanteResponse")
  @ResponseWrapper(localName="consultarSubastasFabricanteResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarSubastasFabricanteResponse")
  @RequestWrapper(localName="consultarSubastasFabricante",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarSubastasFabricante")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="subastas")
  public List<co.com.losalpes.marketplace.ws.types.Subasta> consultarSubastasFabricante(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="nit")
    String nit);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/asignarFabricantesSubasta")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/asignarFabricantesSubasta",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/asignarFabricantesSubastaResponse")
  @ResponseWrapper(localName="asignarFabricantesSubastaResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.AsignarFabricantesSubastaResponse")
  @RequestWrapper(localName="asignarFabricantesSubasta", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.AsignarFabricantesSubasta")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean asignarFabricantesSubasta(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoSubasta")
    String numSeguimientoSubasta, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="fabricantes")
    List<Fabricante> fabricantes);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/consultarFabricantesSubasta")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/consultarFabricantesSubasta",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/consultarFabricantesSubastaResponse")
  @ResponseWrapper(localName="consultarFabricantesSubastaResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarFabricantesSubastaResponse")
  @RequestWrapper(localName="consultarFabricantesSubasta",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarFabricantesSubasta")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="fabricantes")
  public List<Fabricante> consultarFabricantesSubasta(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimiento")
    String numSeguimiento);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionOfertas/consultarSubastaOrdenCompra")
  @Action(input="http://marketplace.losalpes.com.co/GestionOfertas/consultarSubastaOrdenCompra",
    output="http://marketplace.losalpes.com.co/GestionOfertas/GestionSubasta/consultarSubastaOrdenCompraResponse")
  @ResponseWrapper(localName="consultarSubastaOrdenCompraResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarSubastaOrdenCompraResponse")
  @RequestWrapper(localName="consultarSubastaOrdenCompra",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarSubastaOrdenCompra")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="subasta")
  public co.com.losalpes.marketplace.ws.types.Subasta consultarSubastaOrdenCompra(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numSeguimientoPO")
    String numSeguimientoPO);
}
