package co.com.losalpes.marketplace.ws.subastaInversa;

import com.sun.xml.ws.api.addressing.AddressingVersion;
import com.sun.xml.ws.api.addressing.WSEndpointReference;
import com.sun.xml.ws.developer.WSBindingProvider;
import com.sun.xml.ws.message.StringHeader;

import java.util.UUID;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class SubastaInversa_ptClient
{
  @WebServiceRef
  private static Subastainversa_client_ep subastainversa_client_ep;

  private static final AddressingVersion WS_ADDR_VER = AddressingVersion.W3C;

  public static SubastaInversa getSubastaInversa()
  {
    subastainversa_client_ep = new Subastainversa_client_ep();
    SubastaInversa subastaInversa = subastainversa_client_ep.getSubastaInversa_pt();
    return subastaInversa;
  }
}
