package co.com.losalpes.marketplace.ws.subastaInversa;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoSubastaInversa/subastainversa_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoSubastaInversa/SubastaInversa",
  name="SubastaInversa")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.subastaInversa.types.ObjectFactory.class })
public interface SubastaInversa
{
  @WebMethod(action="process")
  @Action(input="process")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoSubastaInversa/SubastaInversa",
    className="co.com.losalpes.marketplace.ws.subastaInversa.types.Process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoSubastaInversa/SubastaInversa",
      name="fechaEntrega")
    XMLGregorianCalendar fechaEntrega, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoSubastaInversa/SubastaInversa",
      name="numSeguimientoSubasta")
    String numSeguimientoSubasta, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoSubastaInversa/SubastaInversa",
      name="nitFabricante")
    String nitFabricante, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoSubastaInversa/SubastaInversa",
      name="valorProducto")
    long valorProducto);
}
