<?binding.jca BAM_bam.jca?>
<wsdl:definitions name="BAM" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/bam/MarketPlace/ProcesoOrdenCompra/BAM" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/bam/MarketPlace/ProcesoOrdenCompra/BAM" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:imp1="http://xmlns.oracle.com/bam" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="writetoBAM_plt">
        <plt:role name="writetoBAM_role">
            <plt:portType name="tns:writetoBAM_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/bam" schemaLocation="xsd/BAMServerConnection1_OrdenCompra.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="_OrdenCompraCollection_msg">
        <wsdl:part name="_OrdenCompraCollection" element="imp1:_OrdenCompraCollection"/>
    </wsdl:message>
    <wsdl:portType name="writetoBAM_ptt">
        <wsdl:operation name="writetoBAM">
            <wsdl:input message="tns:_OrdenCompraCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
