<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GestionCorreoElectronico"
     targetNamespace="http://marketplace.losalpes.com.co/GestionCorreoElectronico/"
     xmlns="http://marketplace.losalpes.com.co/GestionCorreoElectronico"
     xmlns:ns1="http://marketplace.losalpes.com.co/GestionCorreoElectronico/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="GestionCorreoElectronico1">
        <plnk:role name="GestionCorreoElectronico">
            <plnk:portType name="null:GestionCorreoElectronico"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://marketplace.losalpes.com.co/GestionCorreoElectronico/" location="GestionCorreoElectronico.wsdl"/>
</wsdl:definitions>
