package co.com.losalpes.marketplace.ws.contrato;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/AprobarContrato?WSDL",
  targetNamespace="http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato",
  name="AprobarContrato")
public class AprobarContrato
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.contrato.execute.AprobarContrato");
      URL baseUrl = AprobarContrato.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            AprobarContrato.class.getResource("http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/AprobarContrato?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/AprobarContrato?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/AprobarContrato?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/AprobarContrato?WSDL",
          e);
    }
  }

  public AprobarContrato()
  {
    super(wsdlLocationURL,
          new QName("http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato",
                    "AprobarContrato"));
  }

  public AprobarContrato(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public co.com.losalpes.marketplace.ws.contrato.Execute_ptt getExecute_pt()
  {
    return (co.com.losalpes.marketplace.ws.contrato.Execute_ptt) super.getPort(new QName("http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato",
                                                                                                 "execute_pt"),
                                                                                       co.com.losalpes.marketplace.ws.contrato.Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public co.com.losalpes.marketplace.ws.contrato.Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.contrato.Execute_ptt) super.getPort(new QName("http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato",
                                                                                                 "execute_pt"),
                                                                                       co.com.losalpes.marketplace.ws.contrato.Execute_ptt.class,
                                                                                       features);
  }
}
