package co.com.losalpes.marketplace.ws.contrato;

import co.com.losalpes.marketplace.ws.contrato.types.Process;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/AprobarContrato?WSDL",
  targetNamespace="http://oracle.com/sca/soapservice/MarketPlace/ProcesoContratos/AprobarContrato",
  name="execute_ptt")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.contrato.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface Execute_ptt
{
  @WebMethod(operationName="AprobarDesaprobar", action="AprobarDesaprobar")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="AprobarDesaprobar")
  @Oneway
  public void aprobarDesaprobar(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      partName="part1", name="process")
    Process part1);

  @WebMethod(operationName="CerrarContrato", action="CerrarContrato")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="CerrarContrato")
  @Oneway
  public void cerrarContrato(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      partName="part1", name="process")
    co.com.losalpes.marketplace.ws.contrato.types.Process part1);
}
