package co.com.losalpes.marketplace.ws.contrato;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://ecos5.virtual.uniandes.edu.co:7001/soa-infra/services/default/ProcesoContratos/procesocontrato_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
  name="ProcesoContrato")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.contrato.types.ObjectFactory.class })
public interface ProcesoContrato
{
  @WebMethod(action="process")
  @Action(input="process")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
    className="co.com.losalpes.marketplace.ws.contrato.types.Process")
  @Oneway
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="cantidad")
    Integer cantidad, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="comercio")
    co.com.losalpes.marketplace.ws.contrato.types.ComercioBO comercio,
    @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="duracion")
    XMLGregorianCalendar duracion, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="estado")
    String estado, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="fabricante")
    co.com.losalpes.marketplace.ws.contrato.types.FabricanteBO fabricante,
    @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="fechaInicio")
    XMLGregorianCalendar fechaInicio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="fechaRegistro")
    XMLGregorianCalendar fechaRegistro, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="id")
    Long id, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="periodicidad")
    String periodicidad, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="precio")
    Long precio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoContratos/ProcesoContrato",
      name="producto")
    co.com.losalpes.marketplace.ws.contrato.types.ProductoBO producto);
}
