package co.com.losalpes.marketplace.ws.gestionCliente;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionCliente?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionCliente",
  name="GestionClienteSOAPQSService")
public class GestionClienteSOAPQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionCliente.GestionClienteSOAPQSService");
      URL baseUrl = GestionClienteSOAPQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GestionClienteSOAPQSService.class.getResource("http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionCliente?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionCliente?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionCliente?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionCliente?wsdl",
          e);
    }
  }

  public GestionClienteSOAPQSService()
  {
    super(wsdlLocationURL,
          new QName("http://marketplace.losalpes.com.co/GestionCliente",
                    "GestionClienteSOAPQSService"));
  }

  public GestionClienteSOAPQSService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GestionClienteSOAPQSPort")
  public co.com.losalpes.marketplace.ws.gestionCliente.GestionCliente getGestionClienteSOAPQSPort()
  {
    return (co.com.losalpes.marketplace.ws.gestionCliente.GestionCliente) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionCliente",
                                                                                                  "GestionClienteSOAPQSPort"),
                                                                                        co.com.losalpes.marketplace.ws.gestionCliente.GestionCliente.class);
  }

  @WebEndpoint(name="GestionClienteSOAPQSPort")
  public co.com.losalpes.marketplace.ws.gestionCliente.GestionCliente getGestionClienteSOAPQSPort(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.gestionCliente.GestionCliente) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionCliente",
                                                                                                  "GestionClienteSOAPQSPort"),
                                                                                        co.com.losalpes.marketplace.ws.gestionCliente.GestionCliente.class,
                                                                                        features);
  }
}
