package co.com.losalpes.marketplace.ws.ordenCompra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorder_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
  name="PurchaseOrder")
@XmlSeeAlso(
  { co.com.losalpes.marketplace.ws.ordenCompra.types.ObjectFactory.class })
public interface PurchaseOrder
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder/PurchaseOrder/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
    className="co.com.losalpes.marketplace.ws.ordenCompra.types.ProcessResponse")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
    className="co.com.losalpes.marketplace.ws.ordenCompra.types.Process")
  @WebResult(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
    name="numSeguimientoPO")
  public String process(@WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="fechaMaximaEntrega")
    XMLGregorianCalendar fechaMaximaEntrega, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="fechaMaximaSubasta")
    XMLGregorianCalendar fechaMaximaSubasta, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="fecha")
    XMLGregorianCalendar fecha, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="nitComercio")
    String nitComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="nombreComercio")
    String nombreComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="emailComercio")
    String emailComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="direccionComercio")
    String direccionComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="telefonoComercio")
    String telefonoComercio, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="cantidadProducto")
    int cantidadProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="nombreProducto")
    String nombreProducto, @WebParam(targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoOrdenCompra/PurchaseOrder",
      name="categoriaProducto")
    String categoriaProducto);
}
