<wsdl:definitions
     name="DispatchAdvice"
     targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoAvisoDespacho/DispatchAdvice"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/MarketPlace_jws/ProcesoAvisoDespacho/DispatchAdvice"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoAvisoDespacho!1.0/DispatchAdvice.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="DispatchAdvice">
        <plnk:role name="DispatchAdviceProvider">
            <plnk:portType name="client:DispatchAdvice"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoAvisoDespacho/DispatchAdvice"
                 schemaLocation="DispatchAdvice.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DispatchAdviceRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="DispatchAdvice">
        <wsdl:operation name="process">
            <wsdl:input message="client:DispatchAdviceRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="DispatchAdviceBinding" type="client:DispatchAdvice">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoAvisoDespacho/DispatchAdvice"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="dispatchadvice_client_ep">
        <wsdl:port name="DispatchAdvice_pt" binding="client:DispatchAdviceBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoAvisoDespacho/dispatchadvice_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
