package co.com.losalpes.marketplace.ws.gestionFacturacion;

import co.com.losalpes.marketplace.ws.types.Cliente;
import co.com.losalpes.marketplace.ws.types.CuentaFacturacion;
import co.com.losalpes.marketplace.ws.types.ObjectFactory;
import co.com.losalpes.marketplace.ws.types.Transaccion;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionFacturacion?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionFacturacion",
  name="GestionFacturacion")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface GestionFacturacion
{
  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/crearCuentaFacturacion")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/crearCuentaFacturacion",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/crearCuentaFacturacionResponse")
  @ResponseWrapper(localName="crearCuentaFacturacionResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.CrearCuentaFacturacionResponse")
  @RequestWrapper(localName="crearCuentaFacturacion", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.CrearCuentaFacturacion")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="numCuenta")
  public String crearCuentaFacturacion(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="cliente")
    Cliente cliente);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/consultarCuentaFacturacion")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/consultarCuentaFacturacion",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/consultarCuentaFacturacionResponse")
  @ResponseWrapper(localName="consultarCuentaFacturacionResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarCuentaFacturacionResponse")
  @RequestWrapper(localName="consultarCuentaFacturacion", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ConsultarCuentaFacturacion")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="cuentaFacturacion")
  public CuentaFacturacion consultarCuentaFacturacion(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numeroCuenta")
    String numeroCuenta);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/generarFacturaCorte")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/generarFacturaCorte",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/generarFacturaCorteResponse")
  @ResponseWrapper(localName="generarFacturaCorteResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.GenerarFacturaCorteResponse")
  @RequestWrapper(localName="generarFacturaCorte", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.GenerarFacturaCorte")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean generarFacturaCorte(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="corte")
    Integer corte, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="plazo")
    int plazo);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/registrarTransaccion")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/registrarTransaccion",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/registrarTransaccionResponse")
  @ResponseWrapper(localName="registrarTransaccionResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.RegistrarTransaccionResponse")
  @RequestWrapper(localName="registrarTransaccion", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.RegistrarTransaccion")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean registrarTransaccion(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="transaccion")
    List<Transaccion> transaccion, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="numCuenta")
    String numCuenta);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/cambiarEstadoCliente")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/cambiarEstadoCliente",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/cambiarEstadoClienteResponse")
  @ResponseWrapper(localName="cambiarEstadoClienteResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.CambiarEstadoClienteResponse")
  @RequestWrapper(localName="cambiarEstadoCliente", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.CambiarEstadoCliente")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean cambiarEstadoCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="nit")
    String nit, @WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="estado")
    String estado);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/consultarCuentaFacturacionCliente")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/consultarCuentaFacturacionCliente",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/consultarCuentaFacturacionClienteResponse")
  @ResponseWrapper(localName="consultarCuentaFacturacionClienteResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarCuentaFacturacionClienteResponse")
  @RequestWrapper(localName="consultarCuentaFacturacionCliente",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ConsultarCuentaFacturacionCliente")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="cuenta")
  public CuentaFacturacion consultarCuentaFacturacionCliente(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="nit")
    String nit);

  @WebMethod(action="http://marketplace.losalpes.com.co/GestionFacturacion/reportarClientesMorosos")
  @Action(input="http://marketplace.losalpes.com.co/GestionFacturacion/reportarClientesMorosos",
    output="http://marketplace.losalpes.com.co/GestionFacturacion/GestionFacturacion/reportarClientesMorososResponse")
  @ResponseWrapper(localName="reportarClientesMorososResponse",
    targetNamespace="http://marketplace.losalpes.com.co", className="co.com.losalpes.marketplace.ws.types.ReportarClientesMorososResponse")
  @RequestWrapper(localName="reportarClientesMorosos", targetNamespace="http://marketplace.losalpes.com.co",
    className="co.com.losalpes.marketplace.ws.types.ReportarClientesMorosos")
  @WebResult(targetNamespace="http://marketplace.losalpes.com.co", name="resultado")
  public boolean reportarClientesMorosos(@WebParam(targetNamespace="http://marketplace.losalpes.com.co",
      name="corte")
    int corte);
}
