package co.com.losalpes.marketplace.ws.gestionRMA;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionRMA?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionRMA", name="GestionRMA")
public class GestionRMA_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA_Service");
      URL baseUrl = GestionRMA_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GestionRMA_Service.class.getResource("http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionRMA?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionRMA?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionRMA?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionRMA?wsdl",
          e);
    }
  }

  public GestionRMA_Service()
  {
    super(wsdlLocationURL,
          new QName("http://marketplace.losalpes.com.co/GestionRMA",
                    "GestionRMA"));
  }

  public GestionRMA_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GestionRMASOAP")
  public co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA getGestionRMASOAP()
  {
    return (co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionRMA",
                                                                                          "GestionRMASOAP"),
                                                                                co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA.class);
  }

  @WebEndpoint(name="GestionRMASOAP")
  public co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA getGestionRMASOAP(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionRMA",
                                                                                          "GestionRMASOAP"),
                                                                                co.com.losalpes.marketplace.ws.gestionRMA.GestionRMA.class,
                                                                                features);
  }
}
