package co.com.losalpes.marketplace.ws.replicacionPricat;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class ReplicacionPricat_ptClient
{
  @WebServiceRef
  private static Replicacionpricat_client_ep replicacionpricat_client_ep;

  public static ReplicacionPricat getReplicacionPricat()
  {
    replicacionpricat_client_ep = new Replicacionpricat_client_ep();
    ReplicacionPricat replicacionPricat = replicacionpricat_client_ep.getReplicacionPricat_pt();
    return replicacionPricat;
  }
}
