<wsdl:definitions
     name="ReturnMaterialAdvice"
     targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoRetornoMaterial!1.0/ReturnMaterialAdvice.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ReturnMaterialAdvice">
        <plnk:role name="ReturnMaterialAdviceProvider">
            <plnk:portType name="client:ReturnMaterialAdvice"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice"
                 schemaLocation="ReturnMaterialAdvice.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ReturnMaterialAdviceRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="ReturnMaterialAdviceResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="ReturnMaterialAdvice">
        <wsdl:operation name="process">
            <wsdl:input message="client:ReturnMaterialAdviceRequestMessage"/>
            <wsdl:output message="client:ReturnMaterialAdviceResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ReturnMaterialAdviceBinding" type="client:ReturnMaterialAdvice">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRetornoMaterial/ReturnMaterialAdvice"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="returnmaterialadvice_client_ep">
        <wsdl:port name="ReturnMaterialAdvice_pt" binding="client:ReturnMaterialAdviceBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoRetornoMaterial/returnmaterialadvice_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
