package co.com.losalpes.marketplace.ws.gestionDA;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionDA?wsdl",
  targetNamespace="http://marketplace.losalpes.com.co/GestionDA", name="GestionDASOAPQSService")
public class GestionDASOAPQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.gestionDA.GestionDASOAPQSService");
      URL baseUrl = GestionDASOAPQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            GestionDASOAPQSService.class.getResource("http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionDA?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionDA?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionDA?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionDA?wsdl",
          e);
    }
  }

  public GestionDASOAPQSService()
  {
    super(wsdlLocationURL,
          new QName("http://marketplace.losalpes.com.co/GestionDA",
                    "GestionDASOAPQSService"));
  }

  public GestionDASOAPQSService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="GestionDASOAPQSPort")
  public co.com.losalpes.marketplace.ws.gestionDA.GestionDA getGestionDASOAPQSPort()
  {
    return (co.com.losalpes.marketplace.ws.gestionDA.GestionDA) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionDA",
                                                                                        "GestionDASOAPQSPort"),
                                                                              co.com.losalpes.marketplace.ws.gestionDA.GestionDA.class);
  }

  @WebEndpoint(name="GestionDASOAPQSPort")
  public co.com.losalpes.marketplace.ws.gestionDA.GestionDA getGestionDASOAPQSPort(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.gestionDA.GestionDA) super.getPort(new QName("http://marketplace.losalpes.com.co/GestionDA",
                                                                                        "GestionDASOAPQSPort"),
                                                                              co.com.losalpes.marketplace.ws.gestionDA.GestionDA.class,
                                                                              features);
  }
}
