<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GestionPO"
     targetNamespace="http://marketplace.losalpes.com.co/GestionPO"
     xmlns="http://ws.pomanager.marketplace.losalpes.com.co/"
     xmlns:ns1="http://marketplace.losalpes.com.co/GestionPO"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="GestionPO">
        <plnk:role name="PoManagerPoManagement">
            <plnk:portType name="null:PoManagerPoManagement"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://marketplace.losalpes.com.co/GestionPO" location="GestionPO.wsdl"/>
</wsdl:definitions>
