<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="VerificacionCrediticia"
     targetNamespace="http://marketplace.losalpes.com.co/VerificacionCrediticia"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:WL5G3N2="http://marketplace.losalpes.com.co/VerificacionCrediticia"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="VerificacionCrediticia_PL">
        <plnk:role name="VerificacionCrediticia_Role">
            <plnk:portType name="WL5G3N2:VerificacionCrediticia"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://marketplace.losalpes.com.co/VerificacionCrediticia" location="http://portal.marketplace.losalpes.com.co:7001/marketPlace/proxy/GestionVerificacionCrediticia?wsdl"/>
</wsdl:definitions>
