<wsdl:definitions
     name="ReplicacionPricat"
     targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoPricat/ReplicacionPricat"
     xmlns:ns1="http://marketplace.losalpes.com.co/GestionFacturacion"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/MarketPlace_jws/ProcesoPricat/ReplicacionPricat"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoPricat!1.0/ReplicacionPricat.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="ReplicacionPricat">
        <plnk:role name="ReplicacionPricatProvider">
            <plnk:portType name="client:ReplicacionPricat"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://marketplace.losalpes.com.co/GestionFacturacion" location="GestionFacturacion.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoPricat/ReplicacionPricat"
                 schemaLocation="ReplicacionPricat.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="ReplicacionPricatRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="ReplicacionPricat">
        <wsdl:operation name="process">
            <wsdl:input message="client:ReplicacionPricatRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ReplicacionPricatBinding" type="client:ReplicacionPricat">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoPricat/ReplicacionPricat"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="replicacionpricat_client_ep">
        <wsdl:port name="ReplicacionPricat_pt" binding="client:ReplicacionPricatBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoPricat/replicacionpricat_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
