<wsdl:definitions
     name="RegistroEntidad"
     targetNamespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoRegistro!1.0/RegistroEntidad.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="RegistroEntidad">
        <plnk:role name="RegistroEntidadProvider">
            <plnk:portType name="client:RegistroEntidad"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad"
                 schemaLocation="RegistroEntidad.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="RegistroEntidadRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="RegistroEntidad">
        <wsdl:operation name="process">
            <wsdl:input message="client:RegistroEntidadRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="RegistroEntidadBinding" type="client:RegistroEntidad">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/MarketPlace_jws/ProcesoRegistro/RegistroEntidad"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="registroentidad_client_ep">
        <wsdl:port name="RegistroEntidad_pt" binding="client:RegistroEntidadBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://portal.marketplace.losalpes.com.co:7001/soa-infra/services/default/ProcesoRegistro/registroentidad_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
