package co.com.losalpes.marketplace.ws.ordenCompraDirecta;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://localhost:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorderdirect_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompra/PurchaseOrderDirect",
  name="purchaseorderdirect_client_ep")
public class Purchaseorderdirect_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.com.losalpes.marketplace.ws.ordenCompraDirecta.Purchaseorderdirect_client_ep");
      URL baseUrl = Purchaseorderdirect_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Purchaseorderdirect_client_ep.class.getResource("http://localhost:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorderdirect_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://localhost:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorderdirect_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://localhost:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorderdirect_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://localhost:7001/soa-infra/services/default/ProcesoOrdenCompra/purchaseorderdirect_client_ep?WSDL",
          e);
    }
  }

  public Purchaseorderdirect_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompra/PurchaseOrderDirect",
                    "purchaseorderdirect_client_ep"));
  }

  public Purchaseorderdirect_client_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="PurchaseOrderDirect_pt")
  public co.com.losalpes.marketplace.ws.ordenCompraDirecta.PurchaseOrderDirect getPurchaseOrderDirect_pt()
  {
    return (co.com.losalpes.marketplace.ws.ordenCompraDirecta.PurchaseOrderDirect) super.getPort(new QName("http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompra/PurchaseOrderDirect",
                                                                                                           "PurchaseOrderDirect_pt"),
                                                                                                 co.com.losalpes.marketplace.ws.ordenCompraDirecta.PurchaseOrderDirect.class);
  }

  @WebEndpoint(name="PurchaseOrderDirect_pt")
  public co.com.losalpes.marketplace.ws.ordenCompraDirecta.PurchaseOrderDirect getPurchaseOrderDirect_pt(WebServiceFeature... features)
  {
    return (co.com.losalpes.marketplace.ws.ordenCompraDirecta.PurchaseOrderDirect) super.getPort(new QName("http://xmlns.oracle.com/MarketPlace/ProcesoOrdenCompra/PurchaseOrderDirect",
                                                                                                           "PurchaseOrderDirect_pt"),
                                                                                                 co.com.losalpes.marketplace.ws.ordenCompraDirecta.PurchaseOrderDirect.class,
                                                                                                 features);
  }
}
